apiVersion: apps/v1
kind: Deployment
metadata:
  name: curalesvic-one-deployment
  labels:
    app: curalesvic-one
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailablel: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: curalesvic-one
  template:
    metadata:
      labels:
        app: curalesvic-one
    spec:
      containers:
      - name: curalesvic-one-container
        image: curalesvicmicrosservice.azurecr.io/springboot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 300Mi
            cpu: 500m
          requests:
            memory: 300Mi
            cpu: 500m
      imagePullSecrets:
        - name: regcred
